# Change these first
owner: auteur-org # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: VibeQuiz Landing Page
    url: https://vibequiz.org

  - name: VibeQuiz API
    url: https://api.vibequiz.org/api/topics
    expectedStatusCodes:
      - 200
      - 401 # API might require auth, so 401 is OK (means server is up)

  - name: VibeQuiz API - Questions
    url: https://api.vibequiz.org/api/questions
    expectedStatusCodes:
      - 200
      - 401

status-website:
  # Custom domain for status page
  cname: status.vibequiz.org
  logoUrl: https://vibequiz.org/favicon.svg
  name: VibeQuiz Status
  introTitle: "**VibeQuiz** uptime monitor and status page"
  introMessage: Real-time status and uptime monitoring for VibeQuiz services
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://vibequiz.org
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
